### ISSUE TITLE
Can't get Heuristic Policy to work

### ISSUE THREAD

**Issue by Shushman** [JuliaPOMDP/POMDPExamples.jl#6]
I'm trying to define a heuristic policy that takes the action with max expected single step utility, and I'm trying to define it like `AlphaVectorPolicy`, but I run into an error that the `action` is not being defined correctly. You can reproduce it by running this - https://github.com/JuliaPOMDP/POMDPExamples.jl/blob/solvers/notebooks/Defining-a-Heuristic-Policy.ipynb

**Comment by zsunberg** [comment]
Good idea for an example! I will try to look at it tonight.

**Comment by zsunberg** [comment]
You need to define `POMDPs.action` instead of just `action`. In input [5] you defined a new function `action` in module `Main` rather than creating a new method of `POMDPs.action`. Get ready to tell everyone this multiple times when they start using POMDPs.jl :)

Thanks for working on this notebook!!
